  /**
  
  CRIACAO DA TABELA PARA LOGIN
  
  DATA DE CRIAÇÃO: 01/08/17

**/ 

-- TABELA DE PERFIS
CREATE TABLE PERFIL (
  COD_PERFIL NUMBER NOT NULL,
  NOM_PERFIL VARCHAR2(200) NOT NULL,
  DSC_PERFIL VARCHAR2(500),
  CONSTRAINT PK_PERFILS PRIMARY KEY (COD_PERFIL) USING INDEX TABLESPACE CAPCIELO_I
) TABLESPACE CAPCIELO_D;

CREATE OR REPLACE SYNONYM CAPRW.PERFIL FOR PERFIL;
GRANT SELECT, INSERT, UPDATE ON PERFIL TO CAPRW;

CREATE SEQUENCE SEQ_PERFIL INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE ;
CREATE OR REPLACE SYNONYM CAPRW.SEQ_PERFIL FOR SEQ_PERFIL;
GRANT SELECT ON SEQ_PERFIL TO CAPRW;

-- TABELA DE USUARIO
CREATE TABLE USUARIO (
  COD_USUARIO NUMBER,
  NOM_USUARIO VARCHAR2(255) NOT NULL,
  NOM_LOGIN VARCHAR2(255) NOT NULL,
  DSC_SENHA VARCHAR2(2000) NOT NULL,
  COD_PERFIL NUMBER NOT NULL,
  EMAIL_PERFIL VARCHAR2(255) NOT NULL,
  DAT_CADASTRO DATE,
  DAT_ULTIMO_ACESSO DATE,
  CONSTRAINT PK_COD_USUARIO PRIMARY KEY (COD_USUARIO) USING INDEX TABLESPACE CAPCIELO_I,
  CONSTRAINT UQ_NOM_LOGIN UNIQUE (NOM_LOGIN) USING INDEX TABLESPACE CAPCIELO_I,
  CONSTRAINT UQ_EMAIL_PERFIL UNIQUE (EMAIL_PERFIL) USING INDEX TABLESPACE CAPCIELO_I,
  CONSTRAINT FK_USUARIO_PERFILS FOREIGN KEY (COD_PERFIL) REFERENCES PERFIL (COD_PERFIL)
) TABLESPACE CAPCIELO_D;


GRANT SELECT, UPDATE, INSERT ON USUARIO TO CAPRW;
CREATE OR REPLACE SYNONYM CAPRW.USUARIO FOR USUARIO;